name: Deploy Frontend to S3 and CloudFront

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::848641374235:role/GitHubActionsFrontendDeployPolicy
          aws-region: us-east-1

      - name: Sync Files to S3
        run: |
          aws s3 sync . s3://walter-canales-resume-frontend --delete --exclude ".git/*" --exclude ".github/*"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E6L7BX5G5UNIO --paths "/*"